import 'package:drift/drift.dart' show Value;
import 'package:flutter_test/flutter_test.dart';
import 'package:keel/core/database/database.dart';

void main() {
  late AppDatabase db;

  setUp(() async {
    db = AppDatabase.memory();
    // Seed: a programme and a project on the same machine.
    await db.projectDao.insertProject(ProjectsCompanion.insert(
      id: 'prog',
      name: 'Big Programme',
      kind: const Value('programme'),
    ));
    await db.projectDao.insertProject(ProjectsCompanion.insert(
      id: 'proj',
      name: 'Sub Project',
    ));
  });

  tearDown(() async => db.close());

  group('generateCodeForEntity', () {
    test('returns a KL-prefixed share string with a secret, and stores the '
        'routing code + secret', () async {
      final share = await db.programmeLinksDao.generateCodeForEntity(
        ownerEntityId: 'prog',
        ownerKind: 'programme',
      );
      expect(share, startsWith('KL-'));
      // Share = routingCode#secret; only the routing code is stored in
      // `code`, the secret lands in `linkSecret`.
      expect(share, contains('#'));
      final routing = share.split('#').first;
      final secret = share.split('#').last;
      final rows = await db.programmeLinksDao.getLinksForEntity('prog');
      expect(rows, hasLength(1));
      expect(rows.single.code, routing);
      expect(rows.single.linkSecret, secret);
      expect(secret, isNotEmpty);
      expect(rows.single.status, 'pending_remote');
      expect(rows.single.generatedHere, isTrue);
      expect(rows.single.partnerKind, 'project');
    });

    test('two generations produce distinct codes', () async {
      final a = await db.programmeLinksDao.generateCodeForEntity(
          ownerEntityId: 'prog', ownerKind: 'programme');
      final b = await db.programmeLinksDao.generateCodeForEntity(
          ownerEntityId: 'prog', ownerKind: 'programme');
      expect(a, isNot(equals(b)));
    });
  });

  group('redeemCode — same-machine', () {
    test(
        'project redeems a code generated by a same-machine programme: '
        'both sides activate and cache each other\'s ids', () async {
      final code = await db.programmeLinksDao.generateCodeForEntity(
        ownerEntityId: 'prog',
        ownerKind: 'programme',
      );
      final res = await db.programmeLinksDao.redeemCode(
        code: code,
        ownerEntityId: 'proj',
        ownerKind: 'project',
      );
      expect(res.outcome, RedeemOutcome.activatedLocally);

      final projLinks =
          await db.programmeLinksDao.getLinksForEntity('proj');
      expect(projLinks, hasLength(1));
      expect(projLinks.single.status, 'active');
      expect(projLinks.single.partnerLocalId, 'prog');
      expect(projLinks.single.partnerName, 'Big Programme');

      final progLinks =
          await db.programmeLinksDao.getLinksForEntity('prog');
      expect(progLinks, hasLength(1));
      expect(progLinks.single.status, 'active');
      expect(progLinks.single.partnerLocalId, 'proj');
      expect(progLinks.single.partnerName, 'Sub Project');
    });

    test('redeem accepts codes with whitespace + mixed case', () async {
      final code = await db.programmeLinksDao.generateCodeForEntity(
        ownerEntityId: 'prog',
        ownerKind: 'programme',
      );
      final messy = '   ${code.toLowerCase().replaceAll('-', ' - ')}  ';
      final res = await db.programmeLinksDao.redeemCode(
        code: messy,
        ownerEntityId: 'proj',
        ownerKind: 'project',
      );
      expect(res.outcome, RedeemOutcome.activatedLocally);
    });

    test('redeeming the same code twice from the same side is a no-op',
        () async {
      final code = await db.programmeLinksDao.generateCodeForEntity(
        ownerEntityId: 'prog',
        ownerKind: 'programme',
      );
      await db.programmeLinksDao.redeemCode(
        code: code,
        ownerEntityId: 'proj',
        ownerKind: 'project',
      );
      final second = await db.programmeLinksDao.redeemCode(
        code: code,
        ownerEntityId: 'proj',
        ownerKind: 'project',
      );
      expect(second.outcome, RedeemOutcome.alreadyLinked);
      // Still exactly one row on the project side.
      expect(
        (await db.programmeLinksDao.getLinksForEntity('proj')),
        hasLength(1),
      );
    });
  });

  group('redeemCode — cross-machine', () {
    test(
        'redeeming a code whose partner isn\'t local lands as '
        'pending_remote', () async {
      // No generator on this machine — simulate a code the user got
      // from a remote programme manager.
      final res = await db.programmeLinksDao.redeemCode(
        code: 'KL-XXXX-XXXX-XXXX',
        ownerEntityId: 'proj',
        ownerKind: 'project',
        partnerNameHint: 'Remote Programme',
      );
      expect(res.outcome, RedeemOutcome.pendingRemote);
      final row = (await db.programmeLinksDao.getLinksForEntity('proj'))
          .single;
      expect(row.status, 'pending_remote');
      expect(row.partnerLocalId, isNull);
      expect(row.partnerName, 'Remote Programme');
    });
  });

  group('revokeLink', () {
    test('revoking an active same-machine link revokes both sides',
        () async {
      final code = await db.programmeLinksDao.generateCodeForEntity(
        ownerEntityId: 'prog',
        ownerKind: 'programme',
      );
      final redeem = await db.programmeLinksDao.redeemCode(
        code: code,
        ownerEntityId: 'proj',
        ownerKind: 'project',
      );
      await db.programmeLinksDao.revokeLink(redeem.id);
      final progRow =
          (await db.programmeLinksDao.getLinksForEntity('prog')).single;
      final projRow =
          (await db.programmeLinksDao.getLinksForEntity('proj')).single;
      expect(progRow.status, 'revoked');
      expect(projRow.status, 'revoked');
      expect(progRow.partnerLocalId, isNull);
      expect(projRow.partnerLocalId, isNull);
    });
  });

  group('remote-aware paths', () {
    test(
        'redeemCodeWithRemote upgrades a pending row to active when the '
        'server reports the partner has joined', () async {
      final fake = _FakeGateway();
      // Server knows the code: server-side already has side A (the
      // remote programme manager) and our PM is about to claim side B.
      fake.preloadActiveCode(
        code: 'KL-AAAA-BBBB-CCCC',
        sideA: const RemoteLinkParty(
          userId: 'remote-user',
          entityId: 'remote-prog',
          kind: 'programme',
          name: 'Remote Programme',
        ),
      );
      final res = await db.programmeLinksDao.redeemCodeWithRemote(
        code: 'KL-AAAA-BBBB-CCCC',
        ownerEntityId: 'proj',
        ownerKind: 'project',
        ownerName: 'Sub Project',
        remoteUserId: 'me',
        remote: fake,
      );
      expect(res.outcome, RedeemOutcome.activatedLocally);
      final row =
          (await db.programmeLinksDao.getLinksForEntity('proj')).single;
      expect(row.status, 'active');
      expect(row.partnerName, 'Remote Programme');
    });

    test(
        'redeemCodeWithRemote stays pending when the server says the '
        'partner hasn\'t joined yet', () async {
      final fake = _FakeGateway();
      // Server has only side A but no side B — claim should respond
      // with non-active state.
      fake.preloadPendingCode(code: 'KL-XX');
      final res = await db.programmeLinksDao.redeemCodeWithRemote(
        code: 'KL-XX',
        ownerEntityId: 'proj',
        ownerKind: 'project',
        ownerName: 'Sub Project',
        remoteUserId: 'me',
        remote: fake,
      );
      expect(res.outcome, RedeemOutcome.pendingRemote);
      final row =
          (await db.programmeLinksDao.getLinksForEntity('proj')).single;
      expect(row.status, 'pending_remote');
    });

    test(
        'redeemCodeWithRemote tolerates a thrown gateway error and '
        'keeps the row pending', () async {
      final fake = _FakeGateway(throwOnClaim: true);
      final res = await db.programmeLinksDao.redeemCodeWithRemote(
        code: 'KL-OFFLINE',
        ownerEntityId: 'proj',
        ownerKind: 'project',
        ownerName: 'P',
        remoteUserId: 'me',
        remote: fake,
      );
      expect(res.outcome, RedeemOutcome.pendingRemote);
    });

    test(
        'refreshPendingLinks flips rows the server now reports as '
        'active and leaves the rest alone', () async {
      // Seed two pending rows.
      await db.programmeLinksDao.generateCodeForEntity(
          ownerEntityId: 'proj', ownerKind: 'project');
      final pendingRows =
          await db.programmeLinksDao.getLinksForEntity('proj');
      expect(pendingRows, hasLength(1));
      final pendingCode = pendingRows.single.code;

      final fake = _FakeGateway();
      // Server now reports this code as active with a remote partner.
      fake.preloadActiveCode(
        code: pendingCode,
        sideA: const RemoteLinkParty(
          userId: 'remote-pm-user',
          entityId: 'remote-prog',
          kind: 'programme',
          name: 'Remote Programme',
        ),
      );

      final activated =
          await db.programmeLinksDao.refreshPendingLinks(
        remoteUserId: 'me',
        remote: fake,
      );
      expect(activated, 1);
      final row =
          (await db.programmeLinksDao.getLinksForEntity('proj')).single;
      expect(row.status, 'active');
      expect(row.partnerName, 'Remote Programme');
    });

    test('refreshPendingLinks with no gateway returns 0 cleanly',
        () async {
      await db.programmeLinksDao.generateCodeForEntity(
          ownerEntityId: 'proj', ownerKind: 'project');
      final n = await db.programmeLinksDao.refreshPendingLinks(
        remoteUserId: null,
        remote: null,
      );
      expect(n, 0);
    });
  });
}

/// Test double for [RemoteLinksGateway]. Honest about the side-effects
/// it simulates so the test reads like documentation of the contract.
class _FakeGateway implements RemoteLinksGateway {
  final bool throwOnClaim;
  final Map<String, RemoteLinkSnapshot> _byCode = {};

  _FakeGateway({this.throwOnClaim = false});

  /// Server already knows this code with one side claimed; this side
  /// (our caller) joins, making the link active.
  void preloadActiveCode({
    required String code,
    required RemoteLinkParty sideA,
  }) {
    _byCode[code] = RemoteLinkSnapshot(
      code: code,
      sideA: sideA,
      sideB: const RemoteLinkParty(
        userId: 'me',
        entityId: 'proj',
        kind: 'project',
        name: 'Sub Project',
      ),
      isActive: true,
    );
  }

  /// Server knows the code but only one side is filled.
  void preloadPendingCode({required String code}) {
    _byCode[code] = RemoteLinkSnapshot(
      code: code,
      sideA: const RemoteLinkParty(
        userId: 'me',
        entityId: 'proj',
        kind: 'project',
        name: 'Sub Project',
      ),
      sideB: null,
      isActive: false,
    );
  }

  @override
  Future<RemoteLinkSnapshot> claim({
    required String code,
    required String entityId,
    required String kind,
    required String name,
  }) async {
    if (throwOnClaim) throw Exception('offline');
    return _byCode[code] ??
        RemoteLinkSnapshot(
          code: code,
          sideA: RemoteLinkParty(
            userId: 'me',
            entityId: entityId,
            kind: kind,
            name: name,
          ),
          sideB: null,
          isActive: false,
        );
  }

  @override
  Future<RemoteLinkSnapshot?> fetch(String code) async {
    return _byCode[code];
  }

  @override
  Future<void> revoke(String code) async {
    _byCode.remove(code);
  }
}
