import 'package:flutter_test/flutter_test.dart';
import 'package:keel/core/database/database.dart';
import 'package:keel/core/status/status_calculator.dart';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

TimelineActivity _activity({
  required String id,
  required int startMonth,
  String activityType = 'milestone',
  String status = 'not_started',
}) {
  final now = DateTime(2026, 1, 1);
  return TimelineActivity(
    id: id,
    workPackageId: 'wp-1',
    projectId: 'p-test',
    name: id,
    activityType: activityType,
    startMonth: startMonth,
    status: status,
    isCritical: false,
    isBaseline: false,
    sortOrder: 0,
    createdAt: now,
    updatedAt: now,
  );
}

List<String> _ids(List<TimelineActivity> acts) =>
    acts.map((a) => a.id).toList();

void main() {
  // Fixed "today" for all tests: 5 Aug 2026. Month index 0 = Jun 2026,
  // so index 2 = Aug (current), 3 = Sep, 4 = Oct, 6 = Dec.
  final now = DateTime(2026, 8, 5);
  const month0 = '2026-06-01';
  final labels = [
    'Jun 26', 'Jul 26', 'Aug 26', 'Sep 26', 'Oct 26', 'Nov 26', 'Dec 26',
  ];

  group('upcomingMilestones — month0Date anchor', () {
    test('includes milestones inside the 90-day window', () {
      final acts = [
        _activity(id: 'sep', startMonth: 3),
        _activity(id: 'oct', startMonth: 4),
        _activity(id: 'dec', startMonth: 6),
      ];
      final result = StatusCalculator.upcomingMilestones(
          acts, labels, month0Date: month0, now: now);
      expect(_ids(result), ['sep', 'oct']);
    });

    test('a milestone later this month is still upcoming', () {
      final acts = [_activity(id: 'aug', startMonth: 2)];
      final result = StatusCalculator.upcomingMilestones(
          acts, labels, month0Date: month0, now: now);
      expect(_ids(result), ['aug']);
    });

    test('past months are excluded', () {
      final acts = [_activity(id: 'jul', startMonth: 1)];
      final result = StatusCalculator.upcomingMilestones(
          acts, labels, month0Date: month0, now: now);
      expect(result, isEmpty);
    });

    test('completed milestones are excluded', () {
      final acts = [
        _activity(id: 'sep-done', startMonth: 3, status: 'complete'),
        _activity(id: 'sep-open', startMonth: 3),
      ];
      final result = StatusCalculator.upcomingMilestones(
          acts, labels, month0Date: month0, now: now);
      expect(_ids(result), ['sep-open']);
    });

    test('only milestone-type activities are considered', () {
      final acts = [
        _activity(id: 'task', startMonth: 3, activityType: 'activity'),
        _activity(id: 'gate', startMonth: 3, activityType: 'gate'),
        _activity(
            id: 'deadline', startMonth: 4, activityType: 'hard_deadline'),
      ];
      final result = StatusCalculator.upcomingMilestones(
          acts, labels, month0Date: month0, now: now);
      expect(_ids(result), ['gate', 'deadline']);
    });

    test('anchor wins over unparseable labels', () {
      final acts = [_activity(id: 'sep', startMonth: 3)];
      final placeholders = List.generate(12, (i) => 'M$i');
      final result = StatusCalculator.upcomingMilestones(
          acts, placeholders, month0Date: month0, now: now);
      expect(_ids(result), ['sep']);
    });

    test('results sort by month index', () {
      final acts = [
        _activity(id: 'oct', startMonth: 4),
        _activity(id: 'sep', startMonth: 3),
      ];
      final result = StatusCalculator.upcomingMilestones(
          acts, labels, month0Date: month0, now: now);
      expect(_ids(result), ['sep', 'oct']);
    });
  });

  group('upcomingMilestones — label fallback (no month0Date)', () {
    test('parses "MMM yy" labels as generated by the Gantt header', () {
      final acts = [
        _activity(id: 'sep', startMonth: 3),
        _activity(id: 'dec', startMonth: 6),
      ];
      final result =
          StatusCalculator.upcomingMilestones(acts, labels, now: now);
      expect(_ids(result), ['sep']);
    });

    test('parses "MMM YYYY" labels', () {
      final acts = [_activity(id: 'sep', startMonth: 1)];
      final result = StatusCalculator.upcomingMilestones(
          acts, ['Aug 2026', 'Sep 2026'], now: now);
      expect(_ids(result), ['sep']);
    });

    test('bare "MMM" labels assume current or next year', () {
      final acts = [_activity(id: 'sep', startMonth: 1)];
      final result = StatusCalculator.upcomingMilestones(
          acts, ['Aug', 'Sep'], now: now);
      expect(_ids(result), ['sep']);
    });

    test('placeholder "M3" labels yield no matches rather than crashing', () {
      final acts = [_activity(id: 'sep', startMonth: 3)];
      final placeholders = List.generate(12, (i) => 'M$i');
      final result =
          StatusCalculator.upcomingMilestones(acts, placeholders, now: now);
      expect(result, isEmpty);
    });

    test('out-of-range month index is skipped', () {
      final acts = [_activity(id: 'beyond', startMonth: 40)];
      final result =
          StatusCalculator.upcomingMilestones(acts, labels, now: now);
      expect(result, isEmpty);
    });
  });
}
